apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: felhoalapu-elosztott-rendszerek-laboratorium
  namespace: django-iac
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/borpatika/Felhoalapu-elosztott-rendszerek-laboratorium'
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'felhoalapu-elosztott-rendszerek-laboratorium:latest'
  triggers:
    - type: ConfigChange
